[workspace]
members = ["csta", "csta_core", "csta_derive", "csta_examples", "csta_montecarlo", "csta_tests", "csta_examples/ising", "csta_metropoli"]
resolver = "2"

package.edition = "2024"
package.authors = ["Carlos Femenias"]
package.license = "./LICENSE"
package.readme = "./README.md"
