[package]
name = "csta_montecarlo"
version = "2.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
rand = "^0.9"
csta_core = { path = "../csta_core", version = "^2.0.0" }